[package]
name = "apr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alkali = ">=0.3.0"
bitflags = ">=2.3.3"
gethostname = ">=0.4.3"
git-version = ">=0.3.5"
mdns-sd = { version = ">=0.7.3" }
network-interface = ">=1.0.1"
